import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormBuilder, FormGroup, Validators, ReactiveFormsModule } from '@angular/forms';
import { Router, RouterModule } from '@angular/router';
import { InventoryService } from '../services/inventory.service';
import { StockAdjustmentType, StockAdjustment } from '../models/inventory.model';
import { ConfirmDialogComponent, LoaderComponent } from '@app/common';
import { MedicineSearchComponent } from '@app/common/components/medicine-search/medicine-search.component';
import { MedicineSearchService } from '@app/common/components/medicine-search/medicine-search.service';
import { AuditLogService, AuditAction, AuditModule } from '@app/common';

@Component({
  selector: 'app-stock-adjustment',
  standalone: true,
  imports: [
    CommonModule, 
    ReactiveFormsModule, 
    RouterModule, 
    LoaderComponent,
    MedicineSearchComponent
  ],
  templateUrl: './stock-adjustment.component.html',
  styleUrls: ['./stock-adjustment.component.scss']
})
export class StockAdjustmentComponent implements OnInit {
  adjustmentForm!: FormGroup;
  isSubmitting: boolean = false;
  adjustmentTypes = Object.values(StockAdjustmentType);

  constructor(
    private fb: FormBuilder,
    private inventoryService: InventoryService,
    private medicineSearchService: MedicineSearchService,
    private confirmDialog: ConfirmDialogComponent,
    private auditLog: AuditLogService,
    private router: Router
  ) {
    this.initForm();
  }

  ngOnInit(): void {
    this.subscribeToMedicineSelection();
  }

  initForm(): void {
    this.adjustmentForm = this.fb.group({
      medicineId: ['', Validators.required],
      medicineName: ['', Validators.required],
      batchNumber: ['', Validators.required],
      currentStock: [{ value: 0, disabled: true }],
      adjustmentType: ['', Validators.required],
      quantity: ['', [Validators.required, Validators.min(1)]],
      reason: ['', [Validators.required, Validators.minLength(10)]],
      remarks: [''],
      approvalRequired: [true]
    });
  }

  subscribeToMedicineSelection(): void {
    this.medicineSearchService.selectedMedicine$.subscribe(medicine => {
      if (medicine) {
        this.adjustmentForm.patchValue({
          medicineId: medicine.id,
          medicineName: medicine.name
        });
      }
    });

    this.medicineSearchService.selectedBatch$.subscribe(batch => {
      if (batch) {
        this.adjustmentForm.patchValue({
          batchNumber: batch.batchNumber,
          currentStock: batch.quantity
        });
      }
    });
  }

  getAdjustmentTypeLabel(type: StockAdjustmentType): string {
    const labels: { [key in StockAdjustmentType]: string } = {
      [StockAdjustmentType.DAMAGE]: 'Damage',
      [StockAdjustmentType.EXPIRY]: 'Expiry',
      [StockAdjustmentType.THEFT]: 'Theft/Loss',
      [StockAdjustmentType.LOSS]: 'Loss',
      [StockAdjustmentType.CORRECTION]: 'Stock Correction',
      [StockAdjustmentType.RETURN]: 'Return to Supplier',
      [StockAdjustmentType.OTHER]: 'Other'
    };
    return labels[type];
  }

  getAdjustmentTypeClass(type: string): string {
    switch(type) {
      case StockAdjustmentType.DAMAGE:
      case StockAdjustmentType.EXPIRY:
      case StockAdjustmentType.THEFT:
      case StockAdjustmentType.LOSS:
        return 'text-danger';
      case StockAdjustmentType.CORRECTION:
        return 'text-warning';
      case StockAdjustmentType.RETURN:
        return 'text-info';
      default:
        return 'text-secondary';
    }
  }

  async onSubmit(): Promise<void> {
    if (this.adjustmentForm.invalid) {
      Object.keys(this.adjustmentForm.controls).forEach(key => {
        this.adjustmentForm.get(key)?.markAsTouched();
      });
      this.confirmDialog.warning('Invalid Form', 'Please fill all required fields correctly');
      return;
    }

    const formValue = this.adjustmentForm.getRawValue();
    const currentStock = formValue.currentStock;
    const adjustmentQty = formValue.quantity;

    if (adjustmentQty > currentStock) {
      this.confirmDialog.warning(
        'Invalid Quantity', 
        `Adjustment quantity (${adjustmentQty}) cannot exceed current stock (${currentStock})`
      );
      return;
    }

    const confirmed = await this.confirmDialog.confirm(
      'Create Stock Adjustment',
      `Adjust ${adjustmentQty} units of ${formValue.medicineName} (Batch: ${formValue.batchNumber})?\n\nReason: ${formValue.reason}`,
      'Yes, Create',
      'Cancel',
      'warning'
    );

    if (confirmed) {
      this.isSubmitting = true;

      const adjustment: StockAdjustment = {
        id: '', // Will be generated by backend
        medicineId: formValue.medicineId,
        medicineName: formValue.medicineName,
        batchNumber: formValue.batchNumber,
        adjustmentType: formValue.adjustmentType,
        quantity: formValue.quantity,
        currentStock: currentStock,
        newStock: currentStock - formValue.quantity,
        reason: formValue.reason,
        remarks: formValue.remarks || '',
        adjustedBy: 'CURRENT_USER', // Will be set by backend from auth token
        adjustedDate: new Date().toISOString(),
        status: formValue.approvalRequired ? 'PENDING' : 'APPROVED',
        approvedBy: formValue.approvalRequired ? undefined : 'AUTO_APPROVED',
        approvedDate: formValue.approvalRequired ? undefined : new Date().toISOString()
      };

      this.inventoryService.createStockAdjustment(adjustment).subscribe({
        next: (result) => {
          this.confirmDialog.success(
            'Adjustment Created',
            formValue.approvalRequired 
              ? 'Stock adjustment created and pending approval'
              : 'Stock adjustment created and auto-approved'
          );

          this.auditLog.logAction(
            AuditAction.CREATE,
            AuditModule.INVENTORY,
            'StockAdjustment',
            result.id,
            `Created adjustment: ${formValue.adjustmentType} for ${formValue.medicineName} (${formValue.quantity} units)`
          ).subscribe();

          this.isSubmitting = false;
          setTimeout(() => {
            this.router.navigate(['/inventory/adjustments']);
          }, 1500);
        },
        error: (error) => {
          this.isSubmitting = false;
          this.confirmDialog.error('Error', 'Failed to create stock adjustment');
          console.error('Error creating adjustment:', error);
        }
      });
    }
  }

  cancel(): void {
    this.router.navigate(['/inventory/adjustments']);
  }

  isFieldInvalid(fieldName: string): boolean {
    const field = this.adjustmentForm.get(fieldName);
    return !!(field && field.invalid && field.touched);
  }

  getNewStock(): number {
    const current = this.adjustmentForm.get('currentStock')?.value || 0;
    const adjustment = this.adjustmentForm.get('quantity')?.value || 0;
    return Math.max(0, current - adjustment);
  }
}
